apiVersion: "v1"
kind: "Service"
metadata:
  name: "travel-coin-service"
  namespace: "default"
  labels:
    app: "wfe"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "wfe"
  type: "ClusterIP"
